const trackData = [
  {
    id: '1',
    title: 'Guilt',
    author: 'Nero',
    album: 'Welcome Reality',
    time: '4:44',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
  {
    id: '2',
    title: 'Electro',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    time: '2:22',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
  {
    id: '3',
    title: 'I"m fire',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    time: '2:22',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },

  {
    id: '4',
    title: 'Non stop ',
    clarification: ' (Remix)',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    time: '4:12',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
  {
    id: '5',
    title: 'Run Run ',
    clarification: ' (feat. AR/CO)',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    time: '2:54',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
  {
    id: '6',
    title: 'Eyes on Fire ',
    clarification: ' (Zeds Dead Remix)',
    author: 'Blue Foundation, Zeds Dead',
    album: 'Eyes on Fire',
    time: '5:20',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
  {
    id: '7',
    title: 'Mucho Bien ',
    clarification: ' (Hi Profile Remix)',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    time: '3:41',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
  {
    id: '8',
    title: 'Knives n Cherries',
    author: 'minthaze',
    album: 'Captivating',
    time: '1:48',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
  {
    id: '9',
    title: 'How Deep Is Your Love',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    time: '3:32',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
  {
    id: '10',
    title: 'Morena',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
    url: './audio/Bobby_Marleni_-_Dropin.mp3',
  },
]

export default trackData
